DROP TABLE IF EXISTS paises;

CREATE TABLE paises (
  id integer NOT NULL,
  alpha_2 char(2) NOT NULL DEFAULT '',
  alpha_3 char(3) NOT NULL DEFAULT '',
  nombre varchar(75) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);

INSERT INTO paises (id, alpha_2, alpha_3, nombre) VALUES
(8,'al','alb','Albania'),
(20,'ad','and','Andorra'),
(28,'ag','atg','Antigua y Barbuda'),
(32,'ar','arg','Argentina'),
(36,'au','aus','Australia'),
(40,'at','aut','Austria'),
(44,'bs','bhs','Bahamas'),
(52,'bb','brb','Barbados'),
(56,'be','bel','Bélgica'),
(84,'bz','blz','Belice'),
(112,'by','blr','Bielorrusia'),
(68,'bo','bol','Bolivia'),
(70,'ba','bih','Bosnia y Herzegovina'),
(76,'br','bra','Brasil'),
(100,'bg','bgr','Bulgaria'),
(124,'ca','can','Canadá'),
(152,'cl','chl','Chile'),
(170,'co','col','Colombia'),
(188,'cr','cri','Costa Rica'),
(191,'hr','hrv','Croacia'),
(192,'cu','cub','Cuba'),
(208,'dk','dnk','Dinamarca'),
(212,'dm','dma','Dominica'),
(218,'ec','ecu','Ecuador'),
(222,'sv','slv','El Salvador'),
(703,'sk','svk','Eslovaquia'),
(705,'si','svn','Eslovenia'),
(724,'es','esp','España'),
(840,'us','usa','Estados Unidos'),
(233,'ee','est','Estonia'),
(246,'fi','fin','Finlandia'),
(242,'fj','fji','Fiyi'),
(250,'fr','fra','Francia'),
(308,'gd','grd','Granada'),
(300,'gr','grc','Grecia'),
(320,'gt','gtm','Guatemala'),
(328,'gy','guy','Guyana'),
(332,'ht','hti','Haití'),
(340,'hn','hnd','Honduras'),
(348,'hu','hun','Hungría'),
(372,'ie','irl','Irlanda'),
(352,'is','isl','Islandia'),
(584,'mh','mhl','Islas Marshall'),
(90,'sb','slb','Islas Salomón'),
(380,'it','ita','Italia'),
(388,'jm','jam','Jamaica'),
(428,'lv','lva','Letonia'),
(438,'li','lie','Liechtenstein'),
(440,'lt','ltu','Lituania'),
(442,'lu','lux','Luxemburgo'),
(807,'mk','mkd','Macedonia del Norte'),
(470,'mt','mlt','Malta'),
(484,'mx','mex','México'),
(583,'fm','fsm','Micronesia'),
(498,'md','mda','Moldavia'),
(492,'mc','mco','Mónaco'),
(499,'me','mne','Montenegro'),
(520,'nr','nru','Nauru'),
(558,'ni','nic','Nicaragua'),
(578,'no','nor','Noruega'),
(554,'nz','nzl','Nueva Zelanda'),
(528,'nl','nld','Países Bajos'),
(585,'pw','plw','Palaos'),
(591,'pa','pan','Panamá'),
(598,'pg','png','Papúa Nueva Guinea'),
(600,'py','pry','Paraguay'),
(604,'pe','per','Perú'),
(616,'pl','pol','Polonia'),
(620,'pt','prt','Portugal'),
(826,'gb','gbr','Reino Unido'),
(203,'cz','cze','República Checa'),
(214,'do','dom','República Dominicana'),
(642,'ro','rou','Rumania'),
(643,'ru','rus','Rusia'),
(882,'ws','wsm','Samoa'),
(659,'kn','kna','San Cristóbal y Nieves'),
(674,'sm','smr','San Marino'),
(670,'vc','vct','San Vicente y las Granadinas'),
(662,'lc','lca','Santa Lucía'),
(678,'st','stp','Santo Tomé y Príncipe'),
(688,'rs','srb','Serbia'),
(752,'se','swe','Suecia'),
(756,'ch','che','Suiza'),
(740,'sr','sur','Surinam'),
(776,'to','ton','Tonga'),
(780,'tt','tto','Trinidad y Tobago'),
(804,'ua','ukr','Ucrania'),
(858,'uy','ury','Uruguay'),
(548,'vu','vut','Vanuatu'),
(862,'ve','ven','Venezuela'); 