"""change name

Revision ID: 1118c26f6c03
Revises: 44491129a27a
Create Date: 2025-06-20 02:40:14.731034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1118c26f6c03'
down_revision = '44491129a27a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('compania_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_clientes_company_id'), table_name='clientes')
    op.create_index(op.f('ix_clientes_compania_id'), 'clientes', ['compania_id'], unique=False)
    op.drop_constraint(op.f('clientes_company_id_fkey'), 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'companias', ['compania_id'], ['id'])
    op.drop_column('clientes', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_company_id_fkey'), 'clientes', 'companias', ['company_id'], ['id'])
    op.drop_index(op.f('ix_clientes_compania_id'), table_name='clientes')
    op.create_index(op.f('ix_clientes_company_id'), 'clientes', ['company_id'], unique=False)
    op.drop_column('clientes', 'compania_id')
    # ### end Alembic commands ### 