"""Add new fields to tables

Revision ID: 349a88b76b2e
Revises: 
Create Date: 2025-06-02 03:35:20.438544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349a88b76b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordenes_de_trabajo', 'referencia',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tipos_documento', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('tipos_documento', sa.Column('owner_compania_id', sa.UUID(), nullable=True))
    op.add_column('tipos_documento', sa.Column('is_system_wide', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('tipos_documento_nombre_key'), 'tipos_documento', type_='unique')
    op.create_foreign_key('fk_tipos_documento_owner_compania_id', 'tipos_documento', 'companias', ['owner_compania_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tipos_documento_owner_compania_id', 'tipos_documento', type_='foreignkey')
    op.create_unique_constraint(op.f('tipos_documento_nombre_key'), 'tipos_documento', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_column('tipos_documento', 'is_system_wide')
    op.drop_column('tipos_documento', 'owner_compania_id')
    op.drop_column('tipos_documento', 'descripcion')
    op.alter_column('ordenes_de_trabajo', 'referencia',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ### 