"""insert users

Revision ID: 44491129a27a
Revises: d123c967f10f
Create Date: 2025-06-19 04:45:38.075777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid

# revision identifiers, used by Alembic.
revision = '44491129a27a'
down_revision = 'd123c967f10f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    #Insert document types with explicit IDs
    op.execute("""
        INSERT INTO tipos_documento (id, nombre, descripcion) 
        VALUES (1, 'Cédula de Ciudadanía', 'Documento de identificación nacional para ciudadanos colombianos.')
        ON CONFLICT (id) DO NOTHING
    """)
    
    op.execute("""
        INSERT INTO tipos_documento (id, nombre, descripcion) 
        VALUES (2, 'NIT', 'Número de Identificación Tributaria usado por empresas y entidades.')
        ON CONFLICT (id) DO NOTHING
    """)
    
    # Update the sequence to continue from the correct value
    op.execute("""
        SELECT setval('tipos_documento_id_seq', (SELECT MAX(id) FROM tipos_documento))
    """)
    
    # Insert company (now document types definitely exist with ID=2 for NIT)
    company_id = "b7e79a8d-3823-4d10-8c7e-cf1535a4d7f1"
    op.execute(f"""
        INSERT INTO companias (
            id, documento, tipo_documento_id, nombre, email, telefono, 
            pais_id, ciudad, direccion, logo
        ) VALUES (
            '{company_id}',
            '900123456',
            2,
            'TechNova Solutions S.A.S.',
            'contacto@technova.co',
            '+57 601 4891234',
            170,
            'Bogotá',
            'Calle 93 #14-20, Oficina 401',
            'https://logo.clearbit.com/technova.co'
        )
        ON CONFLICT (id) DO NOTHING
    """)
    
    # Insert user with explicit ID and correct enum value
    user_id = str(uuid.uuid4())
    op.execute(f"""
        INSERT INTO usuarios (
            id, company_id, display_name, document_id, document_type_id,
            email, phone_number, rol, nivel, zona_geografica_id,
            photo_url, is_active, uid
        ) VALUES (
            '{user_id}',
            '{company_id}',
            'Cristhian Sánchez',
            '123456789',
            1,
            'ccdelgadop@gmail.com',
            '+57 310 9876543',
            'SUPER_ADMIN',
            NULL,
            NULL,
            'https://randomuser.me/api/portraits/women/45.jpg',
            true,
            'ITv1cnNrIUWQ0Fkh2ehYO4FQNYy2'
        )
        ON CONFLICT (uid) DO NOTHING
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up in reverse order
    op.execute("DELETE FROM usuarios WHERE uid = 'ITv1cnNrIUWQ0Fkh2ehYO4FQNYy2'")
    op.execute("DELETE FROM companias WHERE id = 'b7e79a8d-3823-4d10-8c7e-cf1535a4d7f1'")
    op.execute("DELETE FROM tipos_documento WHERE id IN (1, 2)")
    # ### end Alembic commands ### 