"""add users to client

Revision ID: 6f0c16e278b2
Revises: 73eccfb252a0
Create Date: 2025-07-13 17:04:43.366589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0c16e278b2'
down_revision = '73eccfb252a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_usuarios_clientes', 'usuarios', 'clientes', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_clientes', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'client_id')
    # ### end Alembic commands ### 