"""se actualiza campo de cliente id en proyectos y ordenes de trabajo para tomarlo de Firebase

Revision ID: 73eccfb252a0
Revises: 44491129a27a
Create Date: 2025-06-21 19:03:48.185545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '73eccfb252a0'
down_revision = '44491129a27a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check and drop foreign key constraints if they exist
    conn = op.get_bind()
    
    # Check if ordenes_de_trabajo constraint exists and drop it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'ordenes_de_trabajo' 
        AND constraint_name = 'ordenes_de_trabajo_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if result.fetchone():
        op.drop_constraint('ordenes_de_trabajo_cliente_id_fkey', 'ordenes_de_trabajo', type_='foreignkey')
    
    op.alter_column('ordenes_de_trabajo', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    
    # Check if proyectos constraint exists and drop it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'proyectos' 
        AND constraint_name = 'proyectos_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if result.fetchone():
        op.drop_constraint('proyectos_cliente_id_fkey', 'proyectos', type_='foreignkey')
    
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    
    # Check if unidades constraint exists and drop it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'unidades' 
        AND constraint_name = 'unidades_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if result.fetchone():
        op.drop_constraint('unidades_cliente_id_fkey', 'unidades', type_='foreignkey')
    
    op.alter_column('unidades', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First convert columns back to UUID
    op.alter_column('unidades', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    
    op.alter_column('ordenes_de_trabajo', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    
    # Then create foreign key constraints if they don't exist
    conn = op.get_bind()
    
    # Check if unidades constraint exists before creating it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'unidades' 
        AND constraint_name = 'unidades_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if not result.fetchone():
        op.create_foreign_key('unidades_cliente_id_fkey', 'unidades', 'clientes', ['cliente_id'], ['id'])
    
    # Check if proyectos constraint exists before creating it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'proyectos' 
        AND constraint_name = 'proyectos_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if not result.fetchone():
        op.create_foreign_key('proyectos_cliente_id_fkey', 'proyectos', 'clientes', ['cliente_id'], ['id'])
    
    # Check if ordenes_de_trabajo constraint exists before creating it
    result = conn.execute(text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'ordenes_de_trabajo' 
        AND constraint_name = 'ordenes_de_trabajo_cliente_id_fkey'
        AND table_schema = 'public'
    """))
    if not result.fetchone():
        op.create_foreign_key('ordenes_de_trabajo_cliente_id_fkey', 'ordenes_de_trabajo', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ### 