"""se actualiza campo de cliente id en proyectos y ordenes de trabajo para tomarlo de Firebase

Revision ID: 73eccfb252a0
Revises: 44491129a27a
Create Date: 2025-06-21 19:03:48.185545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73eccfb252a0'
down_revision = '44491129a27a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ordenes_de_trabajo_cliente_id_fkey'), 'ordenes_de_trabajo', type_='foreignkey')
    op.alter_column('ordenes_de_trabajo', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('proyectos_cliente_id_fkey'), 'proyectos', type_='foreignkey')
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('unidades_cliente_id_fkey'), 'unidades', type_='foreignkey')
    op.alter_column('unidades', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('unidades_cliente_id_fkey'), 'unidades', 'clientes', ['cliente_id'], ['id'])
    op.alter_column('unidades', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(op.f('proyectos_cliente_id_fkey'), 'proyectos', 'clientes', ['cliente_id'], ['id'])
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(op.f('ordenes_de_trabajo_cliente_id_fkey'), 'ordenes_de_trabajo', 'clientes', ['cliente_id'], ['id'])
    op.alter_column('ordenes_de_trabajo', 'cliente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ### 