"""init schema 2025-06-10

Revision ID: 7bb3623a0b06
Revises: d123c967f10f
Create Date: 2025-06-10 20:16:10.830013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bb3623a0b06'
down_revision = 'd123c967f10f'
branch_labels = None
depends_on = None

rol_enum = sa.Enum('ADMIN', 'SUPER_ADMIN', 'SUPERVISOR', 'CLIENT', 'TECHNICIAN',
                   name='rol')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    rol_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'usuarios',
        sa.Column('rol', rol_enum, nullable=False)
    )
    
    op.alter_column('checklist_item_templates', 'evidencia_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_checklist_item_templates_id'), 'checklist_item_templates', ['id'], unique=False)
    op.drop_constraint(op.f('checklist_item_templates_checklist_template_id_fkey'), 'checklist_item_templates', type_='foreignkey')
    op.create_foreign_key(None, 'checklist_item_templates', 'checklist_templates', ['checklist_template_id'], ['id'])
    op.alter_column('checklist_items', 'evidencia_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('checklist_items', 'evidencia_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.drop_constraint(op.f('checklist_items_checklist_id_fkey'), 'checklist_items', type_='foreignkey')
    op.create_foreign_key(None, 'checklist_items', 'checklists', ['checklist_id'], ['id'])
    op.create_index(op.f('ix_checklist_templates_id'), 'checklist_templates', ['id'], unique=False)
    op.alter_column('checklists', 'check_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_index(op.f('ix_checklists_orden_trabajo_id'), 'checklists', ['orden_trabajo_id'], unique=False)
    op.add_column('clientes', sa.Column('pais_id', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('ciudad', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('clientes', sa.Column('logo', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'paises', ['pais_id'], ['id'])
    op.add_column('paises', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('paises', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('paises', 'alpha_2',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('paises', 'alpha_3',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    op.create_unique_constraint(None, 'paises', ['nombre'])
    op.add_column('usuarios', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('usuarios', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('usuarios', sa.Column('document_id', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('document_type_id', sa.Integer(), nullable=False))
    op.add_column('usuarios', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('photo_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'tipos_documento', ['document_type_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'companias', ['company_id'], ['id'])
    op.drop_column('usuarios', 'full_name')
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'photo_url')
    op.drop_column('usuarios', 'phone_number')
    op.drop_column('usuarios', 'document_type_id')
    op.drop_column('usuarios', 'document_id')
    op.drop_column('usuarios', 'company_id')
    op.drop_column('usuarios', 'display_name')
    op.drop_column('usuarios', 'id')
    op.drop_constraint(None, 'paises', type_='unique')
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.alter_column('paises', 'alpha_3',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('paises', 'alpha_2',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.drop_column('paises', 'updated_at')
    op.drop_column('paises', 'created_at')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'logo')
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'ciudad')
    op.drop_column('clientes', 'pais_id')
    op.drop_index(op.f('ix_checklists_orden_trabajo_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.alter_column('checklists', 'check_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_checklist_templates_id'), table_name='checklist_templates')
    op.drop_constraint(None, 'checklist_items', type_='foreignkey')
    op.create_foreign_key(op.f('checklist_items_checklist_id_fkey'), 'checklist_items', 'checklists', ['checklist_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.alter_column('checklist_items', 'evidencia_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('checklist_items', 'evidencia_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'checklist_item_templates', type_='foreignkey')
    op.create_foreign_key(op.f('checklist_item_templates_checklist_template_id_fkey'), 'checklist_item_templates', 'checklist_templates', ['checklist_template_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_checklist_item_templates_id'), table_name='checklist_item_templates')
    op.alter_column('checklist_item_templates', 'evidencia_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    rol_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ### 