"""modify schema

Revision ID: a1b90f80d755
Revises: f9b6483ec305
Create Date: 2025-06-07 02:32:09.267480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b90f80d755'
down_revision = 'f9b6483ec305'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'id')
    # ### end Alembic commands ### 