"""Agregar campos de reporte a Checklist

Revision ID: d6a237fcfa36
Revises: 6f0c16e278b2
Create Date: 2025-08-08 00:50:10.589915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a237fcfa36'
down_revision = '6f0c16e278b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('reporte_prerevision_url', sa.String(), nullable=True))
    op.add_column('checklists', sa.Column('reporte_final_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'reporte_final_url')
    op.drop_column('checklists', 'reporte_prerevision_url')
    # ### end Alembic commands ### 