"""add ordenes_trabajo_seguimiento

Revision ID: dafff93e1194
Revises: 7bb3623a0b06
Create Date: 2025-06-11 16:53:42.464846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafff93e1194'
down_revision = '7bb3623a0b06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_trabajo_seguimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=True),
    sa.Column('evento', sa.Enum('INICIO', 'PAUSA', 'REANUDACION', 'FIN', 'PASO_COMPLETADO', name='evento_orden'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_de_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_trabajo_seguimiento')
    # ### end Alembic commands ### 