"""modify user table

Revision ID: db1cfe9ea2a5
Revises: 349a88b76b2e
Create Date: 2025-06-02 22:47:39.562555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1cfe9ea2a5'
down_revision = '349a88b76b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('document_id', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('document_type_id', sa.Integer(), nullable=False))
    op.add_column('usuarios', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('rol', sa.Enum('ADMIN', 'SUPER_ADMIN', 'SUPERVISOR', 'CLIENT', 'TECHNICIAN', name='rol'), nullable=False))
    op.create_foreign_key(None, 'usuarios', 'tipos_documento', ['document_type_id'], ['id'])
    op.drop_column('usuarios', 'full_name')
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'photo_url')
    op.drop_column('usuarios', 'phone_number')
    op.drop_column('usuarios', 'document_type_id')
    op.drop_column('usuarios', 'document_id')
    op.drop_column('usuarios', 'display_name')
    # ### end Alembic commands ### 