"""PROJECT add fields

Revision ID: ded70a953766
Revises: 6f0c16e278b2
Create Date: 2025-08-14 20:21:37.070259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded70a953766'
down_revision = '6f0c16e278b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('cliente_nombre', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('company_nombre', sa.String(), nullable=True))
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='cliente_id::uuid')
    op.create_foreign_key(None, 'proyectos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proyectos', type_='foreignkey')
    op.alter_column('proyectos', 'cliente_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='cliente_id::varchar')
    op.drop_column('proyectos', 'company_nombre')
    op.drop_column('proyectos', 'cliente_nombre')
    # ### end Alembic commands ### 