"""Add company_id to usuarios

Revision ID: f9b6483ec305
Revises: db1cfe9ea2a5
Create Date: 2025-06-03 03:51:30.474262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b6483ec305'
down_revision = 'db1cfe9ea2a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'usuarios', 'companias', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'company_id')
    # ### end Alembic commands ### 