name: CI - CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 🐳 Build & Push Docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ⬇️ Checkout código
        uses: actions/checkout@v3

      - name: 🔐 Configurar GCP
        uses: ./.github/actions/setup-gcp
        with:
          gpc_credentials: ${{ secrets.VERTIONE_APPLICATION_CREDENTIALS }}
          gpc_project_id: ${{ secrets.VERTIONE_PROJECT_ID }}

      - name: 🐳 Construir y subir imagen Docker
        env:
          GOOGLE_PROJECT: ${{ secrets.VERTIONE_PROJECT_ID }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.VERTIONE_PROJECT_ID }}/artifact-registry-vertione/api
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ⬇️ Checkout código
        uses: actions/checkout@v3

      - name: 🔐 Configurar GCP
        uses: ./.github/actions/setup-gcp
        with:
          gpc_credentials: ${{ secrets.VERTIONE_APPLICATION_CREDENTIALS }}
          gpc_project_id: ${{ secrets.VERTIONE_PROJECT_ID }}

      - name: 🚀 Desplegar imagen Docker
        env:
          GOOGLE_PROJECT: ${{ secrets.VERTIONE_PROJECT_ID }}
        run: |
          gcloud run deploy vertione \
            --image=us-central1-docker.pkg.dev/${{ secrets.VERTIONE_PROJECT_ID }}/artifact-registry-vertione/api \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --max-instances=2 \
            --clear-env-vars \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }},CLOUD_PROJECT_ID=${{ secrets.CLOUD_PROJECT_ID }},FIREBASE_SERVICE_ACCOUNT_JSON=${{ secrets.FIREBASE_CREDENTIALS }}"
